### PR TITLE
debugging

### PR DESCRIPTION
**Pull request by fredrikekre**

### CODE REVIEW

**Comment by simonp0420** [comment]
Accepting this PR temporarily to view the resulting deployed docs.

**Comment by fredrikekre** [comment]
The problem is not in the deployment. Note that I removed lots of code so you should probably revert and we can keep debugging in an open PR.

**Comment by simonp0420** [comment]
Before I saw your latest comment, I re-added all the markdown you removed from examples.md and re-ran your branch with that change.  Everything worked perfectly.  I am now going to revert the PR, and incorporate the one change you made that I think looked possibly significant:  You added PSSFSS to the docs/Project.toml file, where I don't think it was there previously.  I didn't think it was necessary to include the main package in the docs/Project.toml file but perhaps it is.

**Comment by simonp0420** [comment]
Well, that wasn't it.  Your "debug" branch works, and my current iteration doesn't, even though I'm attempting to duplicate your setup in the CI.yml file.  Any ideas?

**Pull request merged**
